iqb-berlin/testcenter

backend/index.php

The `TESTMODE_REAL_DATA-false`-statements in the docker-compose files will set it 'false' sometimes but this evaluated to true.

[Backend] Only accept TESTMODE_REAL_DATA as true, when is it "yes"

---

frontend/src/app/superadmin/settings/settings.component.ts

- Border around settings group removed. It served no purpose and was  misaligned.
- Give the settings column more width.
- Give descriptive name to css class
Vorher:
Nachher:

[frontend] Improve Settings component layout

---

frontend/src/app/app-root/code-input/code-input.component.html
frontend/src/app/app-root/login/login.component.html
frontend/src/app/test-controller/components/unithost/unithost.component.html

This change only concerns input form-fields of testtakers (login, input for code and unithost)

Add outline to user input form-fields. Resolves #74

---

frontend/src/app/sys-check/questionnaire/questionnaire.component.html

Die SysCheck questionaire header bekommen ihren Wert jetzt vorzugsweise vom value/textnode.
<Q id="1" type="header" prompt="Fragebogen zum Systemcheck 1">Value vom Header</Q>
In diesem Beispiel also "Value vom Header". Ist dieser nicht vorhanden, wird zurück auf den prompt gegriffen.
Der Wert des value/textnodes wird im Moment unter q.options gespeichert, ist das so gewollt? Ich hätte erwartet, dass man das unter q.value finden würde.

Syscheck questionare header value from textnode

---

.gitlab-ci.yml

- Only triggered by creating prod build (tags)
- Split up build jobs for the 3 components This is necessary because the scanning report can only be a single file.  By having different jobs, the 3 reports are automatically merged (and  shown on the "Security" tab in GitLab).
- For scanning the tool "trivy" is used. "exit-code 0" means that the job never fails even though issues might  have been found. This is necessary because GitLab does not accept  artifacts (reports) from failed jobs.
The format paramaters are for GitLab, so it can show the results on the  "Security" tab of the pipeline.

Add container-scanning to CI pipeline

---

docs/CHANGELOG.md
frontend/src/app/app-route-guards.ts

Resolves #234.
Ich bin mir hier nicht komplett sicher, ob ich das richtige Problem gefixed habe.
Im Issue redest du von, dass man sich nicht mehr einloggen kann. Aber die Login Maske wurde korrekt geladen?
Bei mir hat das Testcenter nach dem Update nie richtig geladen, sondern war einfach nur eine leere Seite (mit dem Logo und der türkisen Hingergrundfarbe). 
Zusätzlich: Ich weiß nicht ob man mein Vorgehen als Updaten bezeichnen kann. Habe eine ältere Version mit dem Install Skript geladen, mich als Admin eingeloggt und dann den Container runtergefahren. Dann habe ich meine lokale Version hochgefahren (weil das Update Skript nur auf richtige releases ohne meine Änderungen updaten kann) und es damit getestet.

Fix incorrect conditional check

---

backend/src/dao/SuperAdminDAO.class.php
backend/test/unit/dao/SuperAdminDAOTest.php
frontend/src/app/superadmin/workspaces/workspaces.component.html
frontend/src/app/superadmin/workspaces/workspaces.component.ts

Resolves #227.
Im Superadminbereich werden nun für jeden Arbeitsbereich auch das Letzte Änderungsdatum angezeigt.
Was mir allerdings aufgefallen ist, ist dass die Logik hinter dem latest_modification_ts evtl etwas irreführend ist.
Wenn man nur Dateien hinzufügt, dann klappt das alles so wie es sein sollte. 
Wenn man aber die zuletzt geuploadete Datei löscht, so wird nun der Timestamp der vorletzten geuploadeten Datei als letztes Änderungsdatum benutzt und nicht der Zeitpunkt an dem eine Datei gelöscht wurde.

Display last modification date on superadmin workspace

---

docker/backend-entrypoint.sh

Internal communication is always http.
#342

[be] Fix URI to access broadcasting-service to always use HTTP

---

dist-src/docker-compose.prod.tls.yml
dist-src/install.sh

The compose file still referenced the old name, which led to errors.

[infrastructure] Fix TLS config file name in PROD

---

frontend/src/app/test-controller/components/test-controller/test-controller.component.css
frontend/src/app/test-controller/components/test-controller/test-controller.component.html

- Forward and Back buttons now always stay beside the actual unit button
- Reduce the size of unit buttons, so that more of them can be present  before wrapping to the next line
- Use lighter gray for disabled buttons
- Restructure element properties to be more logical (directives first,  outputs last etc)

[frontend] Improve unit navigatin bar styling

---

README.md

Fix for a small typo.
"Broadcasting-Service by Unit-Tets" -> "Broadcasting-Service by Unit-Tests"

Fix for small typo in README.md

---

docker/broadcasting-service.Dockerfile
docker/frontend.Dockerfile
frontend/package.json

Node wurde auf die gewünschte Versiob (20.9.0-bookworm-slim) hochgezogen.
Das fibers package ist nicht mit node 16+ kompatibel. Habe jetzt aber auch nicht gesehen wo das konkret benötigt wurde und deswegen erstmal entfernt. Falls ich was übersehen habe und das dringend notwendig ist, gib gerne Bescheid.

Update fe/bs node version

---

frontend/src/app/superadmin/settings/app-config.component.ts

Ich wollte noch ein klein wenig nachbessern, bei Huanings Verbesserungen (anderer PR). Habe mich dabei gewundert, warum das Logo auf der Admin-Seite manchmal einfach nicht erscheint. Der Grund ist, dass das AppConfig-Object nicht da ist, er aber trotzdem weitermacht, als wäre nix gewesen.
Hier ist der Fix, damit korrekt ein Error kommt.
Allerdings wäre herauszufinden, warum das Object manchmal einfach nicht da ist. Passiert leider nicht immer, aber in ca. 50% der Fälle. Zum reproduzieren einfach immer wieder neu laden.

[frontend] Fix error hiding in super admin settings

---

frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.html
frontend/src/app/shared/components/confirm-dialog/confirm-dialog.component.ts
frontend/src/app/shared/interfaces/confirm-dialog.interfaces.ts
frontend/src/app/test-controller/components/test-controller/test-controller.component.ts

Resolves #441.
Habe für confirmDialog ein optionales cancel button Label hinzugefügt.
Das default Label ist "Abbrechen", falls nichts extra angegeben.

fe:Add optional cancelbutton label for confirmDialog

---

docs/CHANGELOG.md
frontend/src/app/shared/components/page-nav-bar/page-nav-bar.component.ts
frontend/src/app/shared/shared.module.ts
frontend/src/app/sys-check/unit-check/unit-check.component.css
frontend/src/app/sys-check/unit-check/unit-check.component.html
frontend/src/app/sys-check/unit-check/unit-check.component.ts
frontend/src/app/test-controller/components/unithost/unithost.component.css
frontend/src/app/test-controller/components/unithost/unithost.component.html
frontend/src/app/test-controller/components/unithost/unithost.component.ts
frontend/src/styles.css

Use the same paging component in the syscheck and the normal unit host.
Change the way page data is handled: The Verona API serves pages as a  dictionary with page number/indexes as key and page labels as value.  This is now changed to a simple array of labels - the papge index is  implicit. At some point the API will change this but for now it is  transformed in the frontend code.
- Refactor page variables: knownPages is now pageList with simplified  type
- Some small UI and code formatting improvements

[fe] Fix page navigation panel in syscheck and refactor page nav

---

dist-src/.env
dist-src/Makefile
dist-src/docker-compose.prod.tls.yml
dist-src/docker-compose.prod.yml
dist-src/install.sh
dist-src/patches/next.sh
docker/docker-compose.yml

There are again multiple compose files for prod which stack. The switch  (TLS_ENABLED) is used in 
the Makefile, which calls the correct compose files.
Patchdateiname muss angepasst werden.

[env] Add TLS_ENABLED switch back to prod setup

---

docs/CHANGELOG.md
frontend/src/app/test-controller/components/unithost/unithost.component.ts
frontend/src/app/test-controller/interfaces/verona.interfaces.ts
frontend/src/app/test-controller/routing/unit-deactivate.guard.ts

Some older Players did not have stateReportPolicy: 'eager' by default so we have to set it manually although it does not exist since verona4 anymore.

fe: Restore support older (pre Verona4) Players

---

frontend/src/app/app-root/login/login.component.html

Resolves #453.
Das hat sich folgendermaßen bei mir verhalten:
Wenn das Namensfeld leer war bzw der eingegebene Name zu kurz, dann wurd bei Enter das Passwortfeld fokussiert.
Wenn der eingebene Name lang genug (>= 3 Zeichen) war, dann wurde das Formular abgeschickt (wahrscheinlich für passwortlose Logins).
Ich habe jetzt keinen Grund gesehen, dass Passwortfeld zu fokussieren wenn der Name keine gültige Länge hat, deswegen würde ich das einfach entfernen.
Falls es doch eine spezifische Anforderung dafür gab, dann gib gerne Bescheid.

fe/remove pw.focus from login

---

docs/api/components.spec.yml

Resolves #497.
Neben Workspace ID habe ich außerdem noch die ID von accessObject, user und question_def auf integer gesetzt (waren davor auch String oder number)

docs: correct type of id in component schema

---

backend/src/middleware/ErrorHandler.class.php
docs/CHANGELOG.md

resolves #532 
All errors that are not caught, are handled by the ErrorHandler.class.php.
This class outputs the raw body to the client, often times a html-abled web browser. To prevent XSS attacks, all response bodies are html-tag escaped.

escape all html tags in error message body

---

docs/CHANGELOG.md
frontend/src/app/sys-check/report/report.component.ts

At the end of the system check: The snackbar is replaced with a dialog box for better visibility. 
This change was done after feedback from users suggested visibility as a problem.

sys-check confirmation: set dialog box instead of snackbar for better visibility

---

frontend/src/app/test-controller/components/test-controller/test-controller.component.ts

- before: the pagelabel was read once, when the review dialog component was opened and never again
- now: the pagelabel is read from the current state of the pagelabel field in the formgroup within the review-dialog component

[bugfix] insert the right pagelabel for reviews

---

backend/src/files/XMLFileBooklet.class.php
backend/test/unit/files/XMLFilesBookletTest.php

closes #701 
When a unit was used more than one time it could still be referred in a condition by its id. An error occurred when running the booklet, but not in the validation.
Also references in nested conditions where not validated correctly.

Backend: Improve booklet validation

---

scripts/version.js

- these files are now included in the create-new-version.sh
- the schemaLocation is now correctly adjusted to the Version number

include sampledata/system-test files in build step

---

docs/CHANGELOG.md
frontend/src/app/workspace-admin/files/files.component.html
frontend/src/app/workspace-admin/files/files.component.ts

- when too many files are being calculated, the browser freezes under load
- hard cap at 1000 files; when more files exist, the calculation is skipped with a notice in the frontend

fix freezing of browser when calculating file sizes

---

docs/CHANGELOG.md
frontend/src/app/test-controller/components/test-controller/test-controller.component.ts

- set the state with a state change immediately upon starting the timer
- log file now has a row with the maxTime/starttime
- the group monitor immediately shows the current unit, instead of waiting for the first statechange with type 'STEP'

set the state, when starting timer

---

frontend/src/app/group-monitor/group-monitor.component.ts
frontend/src/app/shared/services/component-util.service.ts
frontend/src/app/shared/shared.module.ts

- Before: when first entering the component, one could control all sessions (even pending). Once the check-all toggle was used, this control off pending sessions disappeared, even when the toggle was activated
- (Temporarily) Fixed: Toggling the switch always reloads the entire group-monitor component, and with it the entire state. Couldnt find the bug in the state change for now

reset the group-monitor component on check-all-toggle

---

docs/CHANGELOG.md
frontend/src/app/group-monitor/group-monitor.component.html

- before the order was kind of random, mostly by name, but sometimes by activeState
- now always order by colum 'Teilnehmer'
resolves #876

explicitly set default sorting order in gm

---

docs/CHANGELOG.md
frontend/src/app/test-controller/services/test-controller.service.ts

- rxjs.interval() is not reliable when the focus on the application is lost in the browser, which lead to slower running time or even automatic interval stop
- putting the interval logic inside a webworker lets the code live in own browser thread that doesnt get throttled automatically

run timerclock as webworker

---

broadcasting-service/src/test-session/test-session.service.ts
broadcasting-service/src/testee/testee.service.ts
frontend/src/app/group-monitor/test-session-manager/test-session-manager.service.ts

- a not unsubscribed subscription in the handling of the group monitor websocket testdata lead to the fact that once a group monitor was opened, the subscription would push every _clock$ interval the same state to the application. When one opened two group monitors within the same application (without refreshing in between), two concurrent leaking subscriptions would push their state to the application

fix gm that shows testsessions from wrong group

---

docs/CHANGELOG.md
frontend/src/app/group-monitor/test-session/test-session.component.css
frontend/src/app/group-monitor/test-session/test-session.component.html

- before only the id was shown, resulting in labels like '1'

[GM]: BlockId now shows with an appropriate label

---

backend/src/dao/WorkspaceDAO.class.php
docs/CHANGELOG.md

- when testtakers set new valid_to values, the new value is applied to already running personsessions

update valid_until of person_sessions when the testtakers is edited

---

definitions/custom-texts.json
docs/CHANGELOG.md
docs/pages/custom-texts.md
frontend/src/app/app-root/starter/starter.component.html

resolves #928 
* neue Felder
* `gm_show_monitor` -> Titel für Monitorfunktion -> 'Testgruppen-Überwachung'
* `gm_show_test` -> Titel für Testüberprüfung -> 'Folgende Testhefte stehen für Sie zur Ansicht bereit:'

add customtexts in group-monitor view

---

definitions/custom-texts.json
docs/CHANGELOG.md
docs/pages/custom-texts.md
frontend/src/app/app-root/starter/starter.component.css
frontend/src/app/app-root/starter/starter.component.html
frontend/src/app/app-root/starter/starter.component.ts
frontend/src/app/app.module.ts
frontend/src/styles.css

resolves #933 
* Testleitungskonsole: Die Testhefte werden sind nun in einem Akkordion-Element positioniert und können nach einem extra Klick angezeigt werden. Das räumt visuell das Starter-Menü auf und rückt den Fokus auf die eigentliche Funktionalität der Testleitungkonsole zurück.

Akkordion gm tests

---

docs/CHANGELOG.md
scripts/database/patches.d/16.1.0.sql

* Doppelte Einträge von Booklets (`tests`) werden im Migrationsskript für 16.1.0 nachträglich bereinigt. Die Abhängigkeiten `test_logs`,`test_reviews`, `units` werden auf dem Eintrag der `tests` Tabelle mit der niedrigsten ID vereinigt.

migrate duplicate tests in db

---

Makefile
backend/src/controller/SystemController.class.php
common/src/classes/booklet-config-data.class.ts
definitions/booklet-config.json
docs/CHANGELOG.md
docs/pages/booklet-config.md
frontend/src/app/shared/services/backend.service.ts
frontend/src/app/shared/services/maindata/maindata.service.ts
frontend/src/app/shared/shared.module.ts
frontend/src/app/test-controller/components/test-controller/test-controller.component.html
frontend/src/app/test-controller/components/test-controller/test-controller.component.spec.ts
frontend/src/app/test-controller/components/test-controller/test-controller.component.ts

* Neue `<BookletConfig>` in der Booklet.xml:
* `show_reload_button` - Man kann sich in der Applikation selbst einen Reload Button anzeigen lassen, der sich wie der normale Reload Button des Browsers verhält. Dies ist im Zusammenspiel mit dem Kiosk Modus nützlich, da hier die gesamte Browsernavigation ausgeschaltet ist, aber manchmal dennoch ein Reload gebraucht wird. Default: OFF

Reload button

---

Makefile
backend/Dockerfile
backend/composer.json
backend/config/local.php.ini
scripts/make/dev.mk

- add opcache php extension to cache the php code as bytecode
- reduces the CPU load per request by half
- the downside of showing stale code is not really given, because we don't change php code after deploying a new version of testcenter; with every update the containers are newly built and the cache emptied

add opcache

---

docs/CHANGELOG.md
frontend/src/app/test-controller/services/test-loader.service.ts

- if booklet with adaptivity is reloaded/continued, lazy loading is deactivated, instead EAGER is enforced
resolves #998

force eager loading, if booklet has adaptivity states
