.idea/codeStyles/Project.xml
backend/src/dao/AdminDAO.class.php
backend/test/unit/dao/AdminDAOTest.php
backend/test/unit/dao/SessionDAOTest.php
backend/test/unit/testdata.sql

otherwise re responses from review-groups could not be downloaded.

be: Display groups with reviews but no responses in stats

---

backend/src/dao/SessionDAO.class.php
docs/CHANGELOG.md
scripts/database/patches.d/next.sql

be: Check for workspace-id as well when creating a new login-session

---

frontend/src/app/shared/components/alert/alert.component.ts

Set alert-component to default encapsulation

---

frontend/src/app/sys-check/questionnaire/questionnaire.component.css

Display mc-element radio buttons as block

---

backend/test/unit/files/XMLFileSysCheckTest.php
e2e/cypress/e2e/sys-check.cy.ts
e2e/cypress/e2e/utils.ts
frontend/src/app/app-root/code-input/code-input.component.html
frontend/src/app/app-root/login/login.component.html
frontend/src/app/app-root/starter/starter.component.html
frontend/src/app/shared/components/error/error.component.html
frontend/src/app/sys-check/network-check/network-check.component.html
frontend/src/app/sys-check/network-check/network-check.component.ts
frontend/src/app/sys-check/questionnaire/questionnaire.component.css
frontend/src/app/sys-check/questionnaire/questionnaire.component.html
frontend/src/app/sys-check/questionnaire/questionnaire.component.ts
frontend/src/app/sys-check/report/report.component.css
frontend/src/app/sys-check/report/report.component.html
frontend/src/app/sys-check/report/report.component.ts
frontend/src/app/test-controller/components/test-status/test-status.component.html
frontend/src/app/test-controller/components/unithost/unithost.component.html
frontend/src/iqb-theme1.scss
sampledata/SysCheck.xml

- Fix layout of speed-test
- Improve layoutof all the syscheck pages. The buttons on the last page  are supposed to be both in the left side. Therefore the general styling  (via global stylesheet) had to be removed. In all other places it has  been added.
- Improve data in example syscheck
- IMprove variable naming and code structure

Improve Syscheck

---

backend/composer.json
backend/composer.lock
docker/backend.Dockerfile

backend: Update php to 8.3.2

---

docs/CHANGELOG.md
frontend/src/app/app-root/login/login.component.html
frontend/src/app/app-root/login/login.component.ts

Add problemLevel variable to customize the error severity. Caps-lock  should only warn and not be an error.
#450

[fe] Login: Show caps-lock warning for password field

---

frontend/src/app/shared/services/maindata/maindata.service.ts

fe: show global customtext without reload

---

docs/api/attachment.spec.yml
docs/api/booklet.spec.yml
docs/api/monitor.spec.yml
docs/api/session.spec.yml
docs/api/system.spec.yml
docs/api/test.spec.yml
docs/api/user.spec.yml
docs/api/workspace.spec.yml

docs: make authToken required

---

dist-src/.env
docker/default.env
docker/docker-compose.yml
docs/CHANGELOG.md

env: add restart policy

---

definitions/vo_Unit.xsd
docs/CHANGELOG.md

https://verona-interfaces.github.io/editor/#operation-subscribe-voeDefinitionChangedNotification

Add "ValuePositionLabels" to the Unit.XSD according to the Verona specification

---

backend/src/controller/UserController.class.php
docs/api/user.spec.yml

putWorkspace now return JSON instead of html
putUsers now return JSON instead of html

fix broken e2e tests (putUser and putWorkspace)

---

.idea/php-test-framework.xml
test/api/hooks.js

Reverts iqb-berlin/testcenter#618

Revert "debug shit"

---

backend/src/controller/WorkspaceController.class.php
backend/src/data-collection/FileDeletionReport.php
backend/src/helper/Mode.class.php
backend/src/workspace/SysChecksFolder.class.php
backend/src/workspace/Workspace.class.php
backend/test/unit/controller/WorkspaceControllerTest.php
backend/test/unit/workspace/WorkspaceTest.php
docs/CHANGELOG.md
docs/api/workspace.spec.yml
frontend/src/app/app-root/starter/starter.component.ts
frontend/src/app/sys-check/network-check/network-check.component.ts
frontend/src/app/sys-check/questionnaire/questionnaire.component.ts
frontend/src/app/sys-check/report/report.component.html
frontend/src/app/sys-check/report/report.component.ts
frontend/src/app/sys-check/sys-check-data.service.ts
frontend/src/app/sys-check/sys-check-routing.module.ts
frontend/src/app/sys-check/sys-check.component.ts
frontend/src/app/sys-check/unit-check/unit-check.component.ts
frontend/src/app/sys-check/welcome/welcome.component.css
frontend/src/app/sys-check/welcome/welcome.component.html
frontend/src/app/sys-check/welcome/welcome.component.ts
frontend/src/app/workspace-admin/files/files.interfaces.ts

resolves #642 
resolves #644 
resolves #645 
resolves #647 
resolves #648

add "alwaysNewSession" mode to the "sys-check-login" login-mode

---

docker/docker-compose.yml
file-service/auth/redis_connector.lua
file-service/nginx.conf

resolves #636 
Voraussetzung für Kubernetes Umsetzung

simplify dns resolver settings for nginx-lua script

---

docs/CHANGELOG.md
frontend/src/app/app-route-guards.ts

"jump into" is not activated when logging in directly with username in url (group monitor)

---

backend/initialize.php
backend/src/workspace/Workspace.class.php

War nicht dringend, aber hat mich grad genervt...
closes #628

Initialize: If invalid files are found on start up, show errors on log

---

docs/CHANGELOG.md
frontend/src/app/app-root/starter/starter.component.html

Tabbable starter

---

docs/CHANGELOG.md
frontend/src/app/group-monitor/booklet/booklet.service.ts
frontend/src/app/group-monitor/group-monitor.component.html

fix the button text

---

e2e/cypress/e2e/Groupmonitor/Checking elementary functionality.cy.ts
e2e/cypress/e2e/Groupmonitor/profiles-and-filter.cy.ts
e2e/cypress/e2e/study-monitor.cy.ts
e2e/cypress/e2e/utils.ts
frontend/src/app/app-root/starter/starter.component.html
frontend/src/app/group-monitor/components/add-filter-dialog/add-filter-dialog.component.html
frontend/src/app/group-monitor/group-monitor.component.html
frontend/src/app/group-monitor/test-session/test-session.component.html

* add e2e-tests for GM profiles, there are declared in TT-XML
* add e2e-test for GM individually filter
* add first basic e2e-tests for GM functionality test

e2e-tests GM profiles/filter and first basic GM functionality tests

---

definitions/custom-texts.json
frontend/src/app/group-monitor/test-session/test-session.component.html
frontend/src/app/group-monitor/time-restriction-dialog/time-restriction-dialog.component.html
frontend/src/app/test-controller/components/unithost/unithost.component.html

resolves #818 
resolves #814 
resolves #815

add 'Minuten' as unit unlocking time block

---

definitions/custom-texts.json
docs/CHANGELOG.md
docs/pages/custom-texts.md
frontend/src/app/group-monitor/components/add-filter-dialog/add-filter-dialog.component.html
frontend/src/app/group-monitor/group-monitor.component.html
frontend/src/app/shared/pipes/customtext/customtext.pipe.ts
frontend/src/app/test-controller/components/test-controller/test-controller.component.html
frontend/src/app/test-controller/components/unit-nav-bar/unit-nav-bar.component.html
frontend/src/app/test-controller/components/unit-nav-bar/unit-nav-bar.component.ts
frontend/src/app/test-controller/test-controller.module.ts
scripts/database/patches.d/next.sql

Change labels

---

definitions/custom-texts.json
docs/CHANGELOG.md
docs/pages/custom-texts.md
frontend/src/app/workspace-admin/results/results.component.html
frontend/src/app/workspace-admin/workspace.module.ts

Gm wrong sessions
